stages:
      data_transformation:
            cmd: python src/classifier/pipeline/stage_03_data_transformation.py
            deps:
                  - src/classifier/pipeline/stage_03_data_transformation.py
                  - artifacts/data_correction/train_data.pkl
                  - artifacts/data_correction/val_data.pkl
            params:
                  - data_transformation

            outs:
                  - artifacts/data_transformation/${P}

      model_trainer:
            cmd: python src/classifier/pipeline/stage_04_model_training.py
            deps:
                  - src/classifier/pipeline/stage_04_model_training.py

                  - artifacts/data_transformation/${P}
            params:
                  - model_name
                  - model_trainer_type
                  - N_ITER
                  - metric

      # MODEL_EVALUATION
      model_evaluation:
            cmd: python src/classifier/pipeline/stage_05_model_evaluation.py
            deps:
                  - src/classifier/pipeline/stage_05_model_evaluation.py
                  - artifacts/data_correction/test_data.pkl
            params:
                  - evaluated_data_transformation
                  - evaluated_model_name
