# COMMON
target_col: "HadHeartAttack"
metric: accuracy

# DATA TRANSFORMATION
data_transformation: "3" # id của data_transformation
do_smote: f # t: true, f: false

# MODEL TRAINING
model_name: LGB_4
param_grid_model_desc:
      n_estimators: 100-200
      max_depth: 10-15
      reg_alpha: 0
      reg_lambda: 0
      learning_rate: 1-3
      subsample: 0.7-0.9
      colsample_bytree: 0.7-0.9

model_trainer_type: r # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal
N_ITER: 5 # số tổ hợp chọn khi chạy random search

# MODEL EVALUATION
evaluated_data_transformation: "10"
evaluated_model_name: XGB_1

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/monitor_plot.html"
      target_val_value: 97
      max_val_value: 100
      height_for_annot: 20
      dtick_y_value: 5
