In [ ]:
import os


os.chdir("../")


os.getcwd()


'd:\\DA_workspace\\heart_disease_predictor\\src'

# Thư viện


In [ ]:
import pandas as pd
import numpy as np
from classifier.Mylib import myfuncs
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split
import plotly.express as px


# Đọc dữ liệu


In [ ]:
df = myfuncs.load_python_object("../artifacts/data_ingestion/train_data.pkl")

df.head()


,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,New York,Male,Poor,0.0,20.0,Within past year (anytime less than 12 months ...,No,5.0,1 to 5,Yes,...,1.83,113.40,33.91,Yes,Yes,No,No,"Yes, received tetanus shot but not sure what type",No,Tested positive using home test without a heal...
1,Minnesota,Male,Good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,Yes,6.0,None of them,No,...,1.80,99.79,30.68,Yes,Yes,No,No,"Yes, received tetanus shot but not sure what type",No,Tested positive using home test without a heal...
2,Ohio,Male,Excellent,0.0,1.0,Within past 2 years (1 year but less than 2 ye...,Yes,7.0,None of them,No,...,1.68,60.78,21.63,Yes,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
3,Montana,Female,Good,1.0,0.0,Within past year (anytime less than 12 months ...,Yes,8.0,All,No,...,1.65,98.88,36.28,Yes,Yes,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
4,Minnesota,Female,Fair,2.0,7.0,Within past year (anytime less than 12 months ...,Yes,6.0,1 to 5,Yes,...,1.63,84.82,32.10,No,No,No,Yes,"Yes, received tetanus shot, but not Tdap",No,Yes


Kich thuoc


In [ ]:
df.shape


(397860, 40)

# Xóa các cột không cần thiết 

## Ý nghĩa các cột

| Cot                       | Y nghia                                                               | Don vi | Phan loai |
| ------------------------- | --------------------------------------------------------------------- | ------ | --------- |
| State                     | bang                                                                  | none   | Nominal   |
| Sex                       | gioi tinh                                                             | none   | Nominal   |
| GeneralHealth             | suc khoe chung                                                        | none   | ordinal   |
| PhysicalHealthDays        | so ngay gap van de the chat                                           | none   | numeric   |
| MentalHealthDays          | so ngay gap van de tinh than                                          | none   | numeric   |
| LastCheckupTime           | lan cuoi di kham suc khoe                                             | none   | ordinal   |
| PhysicalActivities        | co tham gia hoat dong the chat khong                                  | none   | binary    |
| SleepHours                | gio ngu trong 1 ngay                                                  | none   | numeric   |
| RemovedTeeth              | so rang da bi loai bo                                                 | none   | nominal   |
| **HadHeartAttack**        | co bi heart attack khong                                              | none   | binary    |
| HadAngina                 | co bi đau thắt ngực                                                   | none   | binary    |
| HadStroke                 | co bi đột quỵ                                                         | none   | binary    |
| HadAsthma                 | co bi hen suyen khong                                                 | none   | binary    |
| HadSkinCancer             | co bi ung thu da khong                                                | none   | binary    |
| HadCOPD                   | co bi Bệnh phổi tắc nghẽn mãn tính                                    | none   | binary    |
| HadDepressiveDisorder     | co bi roi loan tam than khong                                         | none   | binary    |
| HadKidneyDisease          | co bi benh than khong                                                 | none   | binary    |
| HadArthritis              | co bi viêm khớp khong                                                 | none   | binary    |
| HadDiabetes               | co bi tieu duong khong                                                | none   | binary    |
| DeafOrHardOfHearing       | co bi chung kho nghe khong                                            | none   | binary    |
| BlindOrVisionDifficulty   | co bi chung kho nhin khong                                            | none   | binary    |
| DifficultyConcentrating   | co bi chung kho tap trung khong                                       | none   | binary    |
| DifficultyWalking         | co bi chung kho di lai khong                                          | none   | binary    |
| DifficultyDressingBathing | co bi gap kho khan trong viec thay do hay tam rua khong               | none   | binary    |
| DifficultyErrands         | co bi gap kho khan trong viec thuc hien cac cong viec hang ngay khong | none   | binary    |
| SmokerStatus              | muc do hut thuoc truyen thong                                         | none   | ordinal   |
| ECigaretteUsage           | muc do hut thuoc la dien tu                                           | none   | ordinal   |
| _ChestScan_               |                                                                       | none   | remove    |
| _RaceEthnicityCategory_   | chung toc                                                             | none   | remove    |
| AgeCategory               | pham vi tuoi                                                          | none   | nominal   |
| HeightInMeters            | chieu cao                                                             | m      | numeric   |
| WeightInKilograms         | can nang                                                              | kg     | numeric   |
| _BMI_                     | chi so BMI                                                            | none   | remove    |
| AlcoholDrinkers           | co uong ruou khong                                                    | none   | binary    |
| _HIVTesting_              |                                                                       | none   | remove    |
| FluVaxLast12              | đã tiêm vắc xin phòng cúm trong 12 tháng qua hay không.               | none   | binary    |
| PneumoVaxEver             | đã từng tiêm vắc xin phòng phổi (Pneumococcal vaccine) hay chưa       | none   | binary    |
| TetanusLast10Tdap         | muc do tiêm vắc xin phòng uốn ván trong 10 nam qua                    | none   | nominal   |
| _HighRiskLastYear_        |                                                                       | none   | remove    |
| _CovidPos_                |                                                                       | none   | remove    |

PhysicalHealthDays: vd: Nếu một người báo cáo rằng trong 30 ngày qua, họ đã có 5 ngày bị ảnh hưởng bởi cơn đau lưng và không thể hoạt động bình thường, thì giá trị trong cột PhysicalHealthDays la 5.

MentalHealthDays: vd: Nếu một người báo cáo rằng trong 30 ngày qua, họ đã có 5 ngày bị ảnh hưởng bởi tinh than và khong co cam xuc binh thuong, thì giá trị trong cột MentalHealthDays la 5.

Cong thuc tinh $BMI = canNang / chieuCao^2$ -> cac cot HeightInMeters, WeightInKilograms, BMI can loai bo 1 cot di


## **UPDATE** Xoa cac cot khong can thiet

In [ ]:
df = df.drop(
    columns=[
        "ChestScan",
        "RaceEthnicityCategory",
        "BMI",
        "HIVTesting",
        "HighRiskLastYear",
        "CovidPos",
    ]
)

## Tỉ lệ missing các cột

In [ ]:
null_percent = df.isnull().mean() * 100
null_percent = null_percent.sort_values(ascending=False)
null_percent


TetanusLast10Tdap            18.452471
PneumoVaxEver                17.230936
HIVTesting                   14.773036
ChestScan                    12.505907
CovidPos                     11.323078
HighRiskLastYear             11.297190
BMI                          10.882220
FluVaxLast12                 10.501935
AlcoholDrinkers              10.371990
WeightInKilograms             9.376414
ECigaretteUsage               7.940230
SmokerStatus                  7.887699
HeightInMeters                6.370080
DifficultyErrands             5.692706
DifficultyConcentrating       5.369477
DifficultyWalking             5.324235
DifficultyDressingBathing     5.303876
BlindOrVisionDifficulty       4.787362
DeafOrHardOfHearing           4.579249
RaceEthnicityCategory         3.100588
RemovedTeeth                  2.499623
PhysicalHealthDays            2.392299
AgeCategory                   2.001709
MentalHealthDays              1.984869
LastCheckupTime               1.818479
SleepHours               

## Xóa các cột có tỉ lệ missing lớn

Ti le missing cua cot ma lon nhat la nho hon 19% nen Khong xoa cot nao het !


## Kich thuoc con lai


In [ ]:
df.shape


(397860, 40)

# Cấu hình lại tên các cột



## **UPDATE** Đổi tên cột

In [ ]:
df.columns


Index(['State', 'Sex', 'GeneralHealth', 'PhysicalHealthDays',
       'MentalHealthDays', 'LastCheckupTime', 'PhysicalActivities',
       'SleepHours', 'RemovedTeeth', 'HadHeartAttack', 'HadAngina',
       'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'AgeCategory', 'HeightInMeters', 'WeightInKilograms',
       'AlcoholDrinkers', 'FluVaxLast12', 'PneumoVaxEver',
       'TetanusLast10Tdap'],
      dtype='object')

In [ ]:
rename_dict = {
    "State": "State_nom",
    "Sex": "Sex_nom",
    "GeneralHealth": "GeneralHealth_ord",
    "PhysicalHealthDays": "PhysicalHealthDays_num",
    "MentalHealthDays": "MentalHealthDays_num",
    "LastCheckupTime": "LastCheckupTime_ord",
    "PhysicalActivities": "PhysicalActivities_bin",
    "SleepHours": "SleepHours_num",
    "RemovedTeeth": "RemovedTeeth_nom",
    "HadAngina": "HadAngina_bin",
    "HadStroke": "HadStroke_bin",
    "HadAsthma": "HadAsthma_bin",
    "HadSkinCancer": "HadSkinCancer_bin",
    "HadCOPD": "HadCOPD_bin",
    "HadDepressiveDisorder": "HadDepressiveDisorder_bin",
    "HadKidneyDisease": "HadKidneyDisease_bin",
    "HadArthritis": "HadArthritis_bin",
    "HadDiabetes": "HadDiabetes_nom",
    "DeafOrHardOfHearing": "DeafOrHardOfHearing_bin",
    "BlindOrVisionDifficulty": "BlindOrVisionDifficulty_bin",
    "DifficultyConcentrating": "DifficultyConcentrating_bin",
    "DifficultyWalking": "DifficultyWalking_bin",
    "DifficultyDressingBathing": "DifficultyDressingBathing_bin",
    "DifficultyErrands": "DifficultyErrands_bin",
    "SmokerStatus": "SmokerStatus_ord",
    "ECigaretteUsage": "ECigaretteUsage_ord",
    "AgeCategory": "AgeCategory_nom",
    "HeightInMeters": "HeightInMeters_num",
    "WeightInKilograms": "WeightInKilograms_num",
    "AlcoholDrinkers": "AlcoholDrinkers_bin",
    "FluVaxLast12": "FluVaxLast12_bin",
    "PneumoVaxEver": "PneumoVaxEver_bin",
    "TetanusLast10Tdap": "TetanusLast10Tdap_nom",
    "TetanusLast10Tdap": "TetanusLast10Tdap_nom",
    "HadHeartAttack": "HadHeartAttack_target",
}


df = df.rename(columns=rename_dict)

df.columns


,State_nom,Sex_nom,GeneralHealth_ord,PhysicalHealthDays_num,MentalHealthDays_num,LastCheckupTime_ord,PhysicalActivities_bin,SleepHours_num,RemovedTeeth_nom,HadHeartAttack,...,DifficultyErrands_bin,SmokerStatus_ord,ECigaretteUsage_ord,AgeCategory_nom,HeightInMeters_num,WeightInKilograms_num,AlcoholDrinkers_bin,FluVaxLast12_bin,PneumoVaxEver_bin,TetanusLast10Tdap_nom
0,New York,Male,Poor,0.0,20.0,Within past year (anytime less than 12 months ...,No,5.0,1 to 5,Yes,...,No,Former smoker,Not at all (right now),Age 40 to 44,1.83,113.40,Yes,No,No,"Yes, received tetanus shot but not sure what type"
1,Minnesota,Male,Good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,Yes,6.0,None of them,No,...,No,Never smoked,Use them some days,Age 18 to 24,1.80,99.79,Yes,No,No,"Yes, received tetanus shot but not sure what type"
2,Ohio,Male,Excellent,0.0,1.0,Within past 2 years (1 year but less than 2 ye...,Yes,7.0,None of them,No,...,No,Never smoked,Never used e-cigarettes in my entire life,Age 70 to 74,1.68,60.78,Yes,Yes,Yes,"Yes, received tetanus shot but not sure what type"
3,Montana,Female,Good,1.0,0.0,Within past year (anytime less than 12 months ...,Yes,8.0,All,No,...,No,Former smoker,Never used e-cigarettes in my entire life,Age 75 to 79,1.65,98.88,Yes,Yes,Yes,"Yes, received tetanus shot but not sure what type"
4,Minnesota,Female,Fair,2.0,7.0,Within past year (anytime less than 12 months ...,Yes,6.0,1 to 5,Yes,...,No,Former smoker,Never used e-cigarettes in my entire life,Age 65 to 69,1.63,84.82,No,No,Yes,"Yes, received tetanus shot, but not Tdap"


## **UPDATE** Sắp xếp các cột theo đúng thứ tự

In [ ]:
cols = pd.Series(df.columns)
numeric_cols = cols[cols.str.endswith("num")].tolist()
numericCat_cols = cols[cols.str.endswith("numcat")].tolist()
binary_cols = cols[cols.str.endswith("bin")].tolist()
nominal_cols = cols[cols.str.endswith("nom")].tolist()
ordinal_cols = cols[cols.str.endswith("ord")].tolist()
target_col = cols[cols.str.endswith("target")].tolist()[0]


df = df[
    numeric_cols
    + numericCat_cols
    + binary_cols
    + nominal_cols
    + ordinal_cols
    + [target_col]
]


df.head()


,PhysicalHealthDays_num,MentalHealthDays_num,SleepHours_num,HeightInMeters_num,WeightInKilograms_num,PhysicalActivities_bin,HadAngina_bin,HadStroke_bin,HadAsthma_bin,HadSkinCancer_bin,...,Sex_nom,RemovedTeeth_nom,HadDiabetes_nom,AgeCategory_nom,TetanusLast10Tdap_nom,GeneralHealth_ord,LastCheckupTime_ord,SmokerStatus_ord,ECigaretteUsage_ord,HadHeartAttack
0,0.0,20.0,5.0,1.83,113.40,No,Yes,Yes,No,No,...,Male,1 to 5,No,Age 40 to 44,"Yes, received tetanus shot but not sure what type",Poor,Within past year (anytime less than 12 months ...,Former smoker,Not at all (right now),Yes
1,0.0,0.0,6.0,1.80,99.79,Yes,No,No,No,No,...,Male,None of them,No,Age 18 to 24,"Yes, received tetanus shot but not sure what type",Good,Within past 2 years (1 year but less than 2 ye...,Never smoked,Use them some days,No
2,0.0,1.0,7.0,1.68,60.78,Yes,No,No,No,No,...,Male,None of them,No,Age 70 to 74,"Yes, received tetanus shot but not sure what type",Excellent,Within past 2 years (1 year but less than 2 ye...,Never smoked,Never used e-cigarettes in my entire life,No
3,1.0,0.0,8.0,1.65,98.88,Yes,No,No,No,No,...,Female,All,Yes,Age 75 to 79,"Yes, received tetanus shot but not sure what type",Good,Within past year (anytime less than 12 months ...,Former smoker,Never used e-cigarettes in my entire life,No
4,2.0,7.0,6.0,1.63,84.82,Yes,Yes,Yes,Yes,No,...,Female,1 to 5,Yes,Age 65 to 69,"Yes, received tetanus shot, but not Tdap",Fair,Within past year (anytime less than 12 months ...,Former smoker,Never used e-cigarettes in my entire life,Yes


# Kiểm tra kiểu dữ liệu các cột

## Kiểu dữ liệu các cột

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397860 entries, 0 to 397859
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   PhysicalHealthDays_num         388342 non-null  float64
 1   MentalHealthDays_num           389963 non-null  float64
 2   SleepHours_num                 393186 non-null  float64
 3   HeightInMeters_num             372516 non-null  float64
 4   WeightInKilograms_num          360555 non-null  float64
 5   PhysicalActivities_bin         396987 non-null  object 
 6   HadAngina_bin                  394627 non-null  object 
 7   HadStroke_bin                  396915 non-null  object 
 8   HadAsthma_bin                  396577 non-null  object 
 9   HadSkinCancer_bin              395357 non-null  object 
 10  HadCOPD_bin                    396217 non-null  object 
 11  HadDepressiveDisorder_bin      395699 non-null  object 
 12  HadKidneyDisease_bin          

SAI:

- cac cot binary, nominal, ordinal va cot target


## Chuyển kdl = kdl mong muốn + NAN


### Cột PhysicalActivities_bin

In [ ]:
set(map(type, df["PhysicalActivities_bin"]))


{float, str}

In [ ]:
df["PhysicalActivities_bin"].unique()


array(['No', 'Yes', nan], dtype=object)

### Cột HadAngina_bin

Kdl ko mong muon la do missing value


In [ ]:
set(map(type, df["HadAngina_bin"]))


{float, str}

In [ ]:
df["HadAngina_bin"].unique()


array(['Yes', 'No', nan], dtype=object)

### Cột HadStroke_bin

Kdl ko mong muon la do missing value


In [ ]:
set(map(type, df["HadStroke_bin"]))


{float, str}

In [ ]:
df["HadStroke_bin"].unique()


array(['Yes', 'No', nan], dtype=object)

### Cột HadAsthma_bin

Kdl ko mong muon la do missing value


In [ ]:
set(map(type, df["HadAsthma_bin"]))


{float, str}

In [ ]:
df["HadAsthma_bin"].unique()


array(['No', 'Yes', nan], dtype=object)

Các cột trên đều thỏa

### Kiểm tra các cột còn lại

In [ ]:
for col in df.columns.tolist()[9:]:
    print(
        f"Cot: {col} - Kdl: {set(map(type, df[col]))} - Unique: {df[col].unique().tolist()}"
    )


Cot: HadSkinCancer_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['No', 'Yes', nan]
Cot: HadCOPD_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['No', 'Yes', nan]
Cot: HadDepressiveDisorder_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['Yes', 'No', nan]
Cot: HadKidneyDisease_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['No', 'Yes', nan]
Cot: HadArthritis_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['Yes', 'No', nan]
Cot: DeafOrHardOfHearing_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['Yes', 'No', nan]
Cot: BlindOrVisionDifficulty_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['No', 'Yes', nan]
Cot: DifficultyConcentrating_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['No', nan, 'Yes']
Cot: DifficultyWalking_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['Yes', 'No', nan]
Cot: DifficultyDressingBathing_bin - Kdl: {<class 'str'>, <class 'float'>} - Unique: ['No', nan, 'Yes']
Cot: DifficultyErrands_bin - Kdl: 

Tất cả các cột đều thỏa


# Kiểm tra nội dung các cột

## Cột numeric


In [ ]:
df[numeric_cols].describe().loc[["min", "max", "mean"]]


,PhysicalHealthDays_num,MentalHealthDays_num,SleepHours_num,HeightInMeters_num,WeightInKilograms_num
min,0.000000,0.000000,1.000000,0.910000,22.680000
max,30.000000,30.000000,24.000000,2.410000,292.570000
mean,4.325061,4.377502,7.023411,1.702772,83.090508


Co vai diem dang luu y:

- Gia tri max cua `SleepHours_num` la 24h -> tuc la co nguoi ngu 24h/ngay
- Gia tri max cua `HeightInMeters_num` la 2.41m -> nguoi nay qua cao, nhung nguoi cao nhat tren the gioi theo (https://dantri.com.vn/doi-song/cuoc-hoi-ngo-giua-nguoi-dan-ong-cao-nhat-va-nguoi-phu-nu-thap-nhat-the-gioi-20240222135435829.htm#:~:text=(D%C3%A2n%20tr%C3%AD)%20%2D%20Sau%206,v%E1%BB%9Bi%20chi%E1%BB%81u%20cao%202%2C51m.) la 2.51 m
- Gia tri max cua `WeightInKilograms_num` la 292 kg -> qua nang, nhung nguoi nang nhat tren the gioi theo (https://vi.wikipedia.org/wiki/Jon_Brower_Minnoch ) la 640 kg


### **UPDATE** Cột SleepHours_num

Kiem tra phan bo cua cot `SleepHours_num`


In [ ]:
label_percent = df["SleepHours_num"].value_counts() / len(df["SleepHours_num"]) * 100
label_percent = label_percent.sort_index()
label_percent


SleepHours_num
1.0      0.251847
2.0      0.341577
3.0      0.727140
4.0      2.786659
5.0      6.766199
6.0     21.555824
7.0     29.938421
8.0     28.175238
9.0      4.759714
10.0     2.347811
11.0     0.156839
12.0     0.671342
13.0     0.036194
14.0     0.067612
15.0     0.072639
16.0     0.071885
17.0     0.005781
18.0     0.037199
19.0     0.003770
20.0     0.031669
21.0     0.000754
22.0     0.003267
23.0     0.004022
24.0     0.011813
Name: count, dtype: float64

Gio ngu (> 13) chiem ti le rat thap, < 0.1 % -> du lieu bi sai vi khong the ngu nhieu nhu vay duoc, gan cac gia tri nay = null de sau do fill in voi mode


In [ ]:
replaced_value = list(range(13, 24 + 1))
replaced_dict = dict(zip(replaced_value, [np.nan] * len(replaced_value)))
df["SleepHours_num"] = df["SleepHours_num"].replace(replaced_dict)

df["SleepHours_num"].unique()


array([ 5.,  6.,  7.,  8., 12., nan,  4., 10.,  9.,  3.,  2.,  1., 11.])

### UPDATE Cột HeightInMeters_num

Kiem tra phan bo cot HeightInMeters_num


In [ ]:
col_name = "HeightInMeters_num"

fig = px.histogram(x=df[col_name], nbins=50)

fig.show()


Kiem tra ti le nguoi co chieu cao > 2.08


In [ ]:
len(df[df[col_name] > 2.08]) / len(df) * 100


0.022872367164329162

Kiem tra ti le nguoi co chieu cao < 1.37


In [ ]:
len(df[df[col_name] < 1.37]) / len(df) * 100


0.10204594581008394

Kiem tra gia tri ngoai lai nho nhat vuot ngoai Q3 + 1.5 \* IQR


In [ ]:
df_col_name_without_nan = df[col_name].dropna()
nguong = np.percentile(df_col_name_without_nan, 75) + 1.5 * (
    np.percentile(df_col_name_without_nan, 75)
    - np.percentile(df_col_name_without_nan, 25)
)
np.min(df_col_name_without_nan[df_col_name_without_nan > nguong])


2.01

Thay the cac gia tri chieu cao > 2.01 thanh null, sau do fill bang mean


In [ ]:
df[col_name] = df[col_name].apply(lambda x: np.nan if x > 2.01 else x)


### UPDATE Cột WeightInKilograms_num

Kiem tra phan bo cot WeightInKilograms_num


In [ ]:
col_name = "WeightInKilograms_num"

fig = px.histogram(x=df[col_name], nbins=50)

fig.show()


Kiem tra gia tri ngoai lai nho nhat vuot ngoai Q3 + 1.5 \* IQR


In [ ]:
df_col_name_without_nan = df[col_name].dropna()
nguong = np.percentile(df_col_name_without_nan, 75) + 1.5 * (
    np.percentile(df_col_name_without_nan, 75)
    - np.percentile(df_col_name_without_nan, 25)
)
np.min(df_col_name_without_nan[df_col_name_without_nan > nguong])


136.08

Thay the cac gia tri can nang > 136.08 thanh null, sau do fill bang mean


In [ ]:
df[col_name] = df[col_name].apply(lambda x: np.nan if x > 136.08 else x)


## Cột numericcat

- Không có cột nào hết

## Cột binary


In [ ]:
for col in binary_cols:
    print(f"{col} -> {df[col].unique().tolist()}")


PhysicalActivities_bin -> ['No', 'Yes', nan]
HadAngina_bin -> ['Yes', 'No', nan]
HadStroke_bin -> ['Yes', 'No', nan]
HadAsthma_bin -> ['No', 'Yes', nan]
HadSkinCancer_bin -> ['No', 'Yes', nan]
HadCOPD_bin -> ['No', 'Yes', nan]
HadDepressiveDisorder_bin -> ['Yes', 'No', nan]
HadKidneyDisease_bin -> ['No', 'Yes', nan]
HadArthritis_bin -> ['Yes', 'No', nan]
DeafOrHardOfHearing_bin -> ['Yes', 'No', nan]
BlindOrVisionDifficulty_bin -> ['No', 'Yes', nan]
DifficultyConcentrating_bin -> ['No', nan, 'Yes']
DifficultyWalking_bin -> ['Yes', 'No', nan]
DifficultyDressingBathing_bin -> ['No', nan, 'Yes']
DifficultyErrands_bin -> ['No', nan, 'Yes']
AlcoholDrinkers_bin -> ['Yes', 'No', nan]
FluVaxLast12_bin -> ['No', 'Yes', nan]
PneumoVaxEver_bin -> ['No', 'Yes', nan]


Co 3 gia tri yes, no va missing value


## Cột nominal


In [ ]:
for col in nominal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")


State_nom -> ['New York', 'Minnesota', 'Ohio', 'Montana', 'Nebraska', 'Georgia', 'Indiana', 'South Dakota', 'Florida', 'Virgin Islands', 'Pennsylvania', 'Texas', 'Puerto Rico', 'Kentucky', 'Louisiana', 'Vermont', 'Maryland', 'Wisconsin', 'Arizona', 'Kansas', 'Michigan', 'Washington', 'New Mexico', 'Virginia', 'Hawaii', 'Alaska', 'California', 'Tennessee', 'Oklahoma', 'New Jersey', 'Utah', 'Rhode Island', 'Colorado', 'Connecticut', 'Alabama', 'Missouri', 'West Virginia', 'Iowa', 'Delaware', 'Massachusetts', 'North Carolina', 'Idaho', 'Mississippi', 'New Hampshire', 'Wyoming', 'Illinois', 'South Carolina', 'Arkansas', 'North Dakota', 'Oregon', 'District of Columbia', 'Maine', 'Nevada', 'Guam']
Sex_nom -> ['Male', 'Female']
RemovedTeeth_nom -> ['1 to 5', 'None of them', 'All', '6 or more, but not all', nan]
HadDiabetes_nom -> ['No', 'Yes', 'No, pre-diabetes or borderline diabetes', nan, 'Yes, but only during pregnancy (female)']
AgeCategory_nom -> ['Age 40 to 44', 'Age 18 to 24', 'Age 70 

Kiem tra gia tri cot AgeCategory_nom co lap day khong


In [ ]:
col_name = "AgeCategory_nom"

data = (
    pd.Series(df[col_name].unique())
    .dropna()
    .str.split(" ")
    .apply(lambda x: (x[1], x[3]))
)

data = sorted(data, key=lambda x: x[0], reverse=False)

data


[('18', '24'),
 ('25', '29'),
 ('30', '34'),
 ('35', '39'),
 ('40', '44'),
 ('45', '49'),
 ('50', '54'),
 ('55', '59'),
 ('60', '64'),
 ('65', '69'),
 ('70', '74'),
 ('75', '79'),
 ('80', 'older')]

Gia tri cua cot tuoi chay tu 18 den 80 hoac hon


## Cột ordinal


In [ ]:
for col in ordinal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")


GeneralHealth_ord -> ['Poor', 'Good', 'Excellent', 'Fair', 'Very good', nan]
LastCheckupTime_ord -> ['Within past year (anytime less than 12 months ago)', 'Within past 2 years (1 year but less than 2 years ago)', 'Within past 5 years (2 years but less than 5 years ago)', '5 or more years ago', nan]
SmokerStatus_ord -> ['Former smoker', 'Never smoked', nan, 'Current smoker - now smokes every day', 'Current smoker - now smokes some days']
ECigaretteUsage_ord -> ['Not at all (right now)', 'Use them some days', 'Never used e-cigarettes in my entire life', nan, 'Use them every day']


## Cột target


In [ ]:
print(f"{target_col} -> {df[target_col].unique().tolist()}")


HadHeartAttack -> ['Yes', 'No']


# Fill missing value


In [ ]:
df = df.applymap(lambda x: np.nan if x is pd.NA else x)

cat_cols = binary_cols + nominal_cols + ordinal_cols


preprocessor = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="mean"), numeric_cols),
        ("numCat", SimpleImputer(strategy="most_frequent"), numericCat_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols),
        ("target", SimpleImputer(strategy="mean"), [target_col]),
    ]
)

df_filled = preprocessor.fit_transform(df)


df_filled = pd.DataFrame(
    df_filled, columns=numeric_cols + numericCat_cols + cat_cols + [target_col]
)


# Luu preprocessor lai


folder = "../artifacts/data_correction"


os.makedirs(folder, exist_ok=True)


myfuncs.save_python_object(
    file_path=os.path.join(folder, "missing_value_handler.pkl"), obj=preprocessor
)


df_filled.head()


,PhysicalHealthDays_num,MentalHealthDays_num,SleepHours_num,HeightInMeters_num,WeightInKilograms_num,PhysicalActivities_bin,HadAngina_bin,HadStroke_bin,HadAsthma_bin,HadSkinCancer_bin,...,Sex_nom,RemovedTeeth_nom,HadDiabetes_nom,AgeCategory_nom,TetanusLast10Tdap_nom,GeneralHealth_ord,LastCheckupTime_ord,SmokerStatus_ord,ECigaretteUsage_ord,HadHeartAttack
0,0.0,20.0,5.0,1.83,113.4,No,Yes,Yes,No,No,...,Male,1 to 5,No,Age 40 to 44,"Yes, received tetanus shot but not sure what type",Poor,Within past year (anytime less than 12 months ...,Former smoker,Not at all (right now),Yes
1,0.0,0.0,6.0,1.8,99.79,Yes,No,No,No,No,...,Male,None of them,No,Age 18 to 24,"Yes, received tetanus shot but not sure what type",Good,Within past 2 years (1 year but less than 2 ye...,Never smoked,Use them some days,No
2,0.0,1.0,7.0,1.68,60.78,Yes,No,No,No,No,...,Male,None of them,No,Age 70 to 74,"Yes, received tetanus shot but not sure what type",Excellent,Within past 2 years (1 year but less than 2 ye...,Never smoked,Never used e-cigarettes in my entire life,No
3,1.0,0.0,8.0,1.65,98.88,Yes,No,No,No,No,...,Female,All,Yes,Age 75 to 79,"Yes, received tetanus shot but not sure what type",Good,Within past year (anytime less than 12 months ...,Former smoker,Never used e-cigarettes in my entire life,No
4,2.0,7.0,6.0,1.63,84.82,Yes,Yes,Yes,Yes,No,...,Female,1 to 5,Yes,Age 65 to 69,"Yes, received tetanus shot, but not Tdap",Fair,Within past year (anytime less than 12 months ...,Former smoker,Never used e-cigarettes in my entire life,Yes


In [ ]:
df_filled.isnull().sum()


PhysicalHealthDays_num           0
MentalHealthDays_num             0
SleepHours_num                   0
HeightInMeters_num               0
WeightInKilograms_num            0
PhysicalActivities_bin           0
HadAngina_bin                    0
HadStroke_bin                    0
HadAsthma_bin                    0
HadSkinCancer_bin                0
HadCOPD_bin                      0
HadDepressiveDisorder_bin        0
HadKidneyDisease_bin             0
HadArthritis_bin                 0
DeafOrHardOfHearing_bin          0
BlindOrVisionDifficulty_bin      0
DifficultyConcentrating_bin      0
DifficultyWalking_bin            0
DifficultyDressingBathing_bin    0
DifficultyErrands_bin            0
AlcoholDrinkers_bin              0
FluVaxLast12_bin                 0
PneumoVaxEver_bin                0
State_nom                        0
Sex_nom                          0
RemovedTeeth_nom                 0
HadDiabetes_nom                  0
AgeCategory_nom                  0
TetanusLast10Tdap_no

# **UPDATE** Chuyển đổi các cột về đúng kiểu dữ liệu


In [ ]:
df_filled[numeric_cols] = df_filled[numeric_cols].astype("float")
df_filled[numericCat_cols] = df_filled[numericCat_cols].astype("float")

df_filled[cat_cols] = df_filled[cat_cols].astype("category")


df_filled.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397860 entries, 0 to 397859
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype   
---  ------                         --------------   -----   
 0   PhysicalHealthDays_num         397860 non-null  float64 
 1   MentalHealthDays_num           397860 non-null  float64 
 2   SleepHours_num                 397860 non-null  float64 
 3   HeightInMeters_num             397860 non-null  float64 
 4   WeightInKilograms_num          397860 non-null  float64 
 5   PhysicalActivities_bin         397860 non-null  category
 6   HadAngina_bin                  397860 non-null  category
 7   HadStroke_bin                  397860 non-null  category
 8   HadAsthma_bin                  397860 non-null  category
 9   HadSkinCancer_bin              397860 non-null  category
 10  HadCOPD_bin                    397860 non-null  category
 11  HadDepressiveDisorder_bin      397860 non-null  category
 12  HadKidneyDisease

In [ ]:
df_filled.columns


Index(['PhysicalHealthDays_num', 'MentalHealthDays_num', 'SleepHours_num',
       'HeightInMeters_num', 'WeightInKilograms_num', 'PhysicalActivities_bin',
       'HadAngina_bin', 'HadStroke_bin', 'HadAsthma_bin', 'HadSkinCancer_bin',
       'HadCOPD_bin', 'HadDepressiveDisorder_bin', 'HadKidneyDisease_bin',
       'HadArthritis_bin', 'DeafOrHardOfHearing_bin',
       'BlindOrVisionDifficulty_bin', 'DifficultyConcentrating_bin',
       'DifficultyWalking_bin', 'DifficultyDressingBathing_bin',
       'DifficultyErrands_bin', 'AlcoholDrinkers_bin', 'FluVaxLast12_bin',
       'PneumoVaxEver_bin', 'State_nom', 'Sex_nom', 'RemovedTeeth_nom',
       'HadDiabetes_nom', 'AgeCategory_nom', 'TetanusLast10Tdap_nom',
       'GeneralHealth_ord', 'LastCheckupTime_ord', 'SmokerStatus_ord',
       'ECigaretteUsage_ord', 'HadHeartAttack'],
      dtype='object')

# **UPDATE** Thay đổi thứ tự các label trong các cột `ordinal`, `binary`


In [ ]:
bin_values_dict = dict(zip(binary_cols, [["No", "Yes"]] * len(binary_cols)))

for col, value in bin_values_dict.items():
    df_filled[col] = df_filled[col].cat.reorder_categories(value, ordered=True)

ord_values_dict = {
    "GeneralHealth_ord": ["Poor", "Fair", "Good", "Very good", "Excellent"],
    "LastCheckupTime_ord": [
        "5 or more years ago",
        "Within past 5 years (2 years but less than 5 years ago)",
        "Within past 2 years (1 year but less than 2 years ago)",
        "Within past year (anytime less than 12 months ago)",
    ],
    "SmokerStatus_ord": [
        "Current smoker - now smokes every day",
        "Current smoker - now smokes some days",
        "Former smoker",
        "Never smoked",
    ],
    "ECigaretteUsage_ord": [
        "Use them every day",
        "Use them some days",
        "Not at all (right now)",
        "Never used e-cigarettes in my entire life",
    ],
}


for col, value in ord_values_dict.items():
    df_filled[col] = df_filled[col].cat.reorder_categories(value, ordered=True)


In [ ]:
df_filled[target_col] = df_filled[target_col].cat.reorder_categories(
    ["No", "Yes"], ordered=True
)


# **UPDATE** Loại bỏ duplicates


In [ ]:
any(df_filled.duplicated())


True

Co duplicates, ti le la ?


In [ ]:
len(df_filled[df_filled.duplicated]) / len(df_filled) * 100


0.10305132458653797

Bo cac duplicates di


In [ ]:
df_filled = df_filled.drop_duplicates().reset_index(drop=True)
df_filled.head()


,PhysicalHealthDays_num,MentalHealthDays_num,SleepHours_num,HeightInMeters_num,WeightInKilograms_num,PhysicalActivities_bin,HadAngina_bin,HadStroke_bin,HadAsthma_bin,HadSkinCancer_bin,...,Sex_nom,RemovedTeeth_nom,HadDiabetes_nom,AgeCategory_nom,TetanusLast10Tdap_nom,GeneralHealth_ord,LastCheckupTime_ord,SmokerStatus_ord,ECigaretteUsage_ord,HadHeartAttack
0,0.0,20.0,5.0,1.83,113.40,No,Yes,Yes,No,No,...,Male,1 to 5,No,Age 40 to 44,"Yes, received tetanus shot but not sure what type",Poor,Within past year (anytime less than 12 months ...,Former smoker,Not at all (right now),Yes
1,0.0,0.0,6.0,1.80,99.79,Yes,No,No,No,No,...,Male,None of them,No,Age 18 to 24,"Yes, received tetanus shot but not sure what type",Good,Within past 2 years (1 year but less than 2 ye...,Never smoked,Use them some days,No
2,0.0,1.0,7.0,1.68,60.78,Yes,No,No,No,No,...,Male,None of them,No,Age 70 to 74,"Yes, received tetanus shot but not sure what type",Excellent,Within past 2 years (1 year but less than 2 ye...,Never smoked,Never used e-cigarettes in my entire life,No
3,1.0,0.0,8.0,1.65,98.88,Yes,No,No,No,No,...,Female,All,Yes,Age 75 to 79,"Yes, received tetanus shot but not sure what type",Good,Within past year (anytime less than 12 months ...,Former smoker,Never used e-cigarettes in my entire life,No
4,2.0,7.0,6.0,1.63,84.82,Yes,Yes,Yes,Yes,No,...,Female,1 to 5,Yes,Age 65 to 69,"Yes, received tetanus shot, but not Tdap",Fair,Within past year (anytime less than 12 months ...,Former smoker,Never used e-cigarettes in my entire life,Yes


In [ ]:
df_filled.shape


(397450, 34)

# Chia thành tập train + val


In [ ]:
df_train, df_val = train_test_split(
    df_filled, test_size=0.2, stratify=df_filled[target_col], random_state=42
)

myfuncs.save_python_object(os.path.join(folder, "train_data.pkl"), df_train)
myfuncs.save_python_object(os.path.join(folder, "val_data.pkl"), df_val)
